repos:
  - repo: local
    hooks:
      - id: black
        name: Black Python code formatter
        entry: black
        language: conda
        args: [--config=pyproject.toml]
      - id: pylint
        name: pylint Python code linter
        entry: pylint
        language: conda
        args: [--rcfile=.pylintrc]
      