name: code_template
channels:
  - defaults
dependencies:
  - ca-certificates=2022.07.19
  - certifi=2022.6.15
  - openssl=1.1.1q
  - pip=22.1.2
  - python=3.8.13
  - setuptools=63.4.1
  - sqlite=3.39.2
  - wheel=0.37.1
  - pip:
    - anyio==3.6.1
    - astroid==2.12.9
    - attrs==22.1.0
    - black==22.8.0
    - brotli==1.0.9
    - cffi==1.15.1
    - cfgv==3.3.1
    - charset-normalizer==2.1.1
    - colorama==0.4.5
    - configargparse==1.5.3
    - coverage==6.4.4
    - distlib==0.3.6
    - fastapi==0.82.0
    - filelock==3.8.0
    - flask==2.2.2
    - flask-basicauth==0.2.0
    - flask-cors==3.0.10
    - gevent==21.12.0
    - geventhttpclient==2.0.2
    - greenlet==1.1.3
    - h11==0.13.0
    - identify==2.5.5
    - idna==3.3
    - importlib-metadata==4.12.0
    - iniconfig==1.1.1
    - isort==5.10.1
    - itsdangerous==2.1.2
    - jinja2==3.1.2
    - lazy-object-proxy==1.7.1
    - locust==2.12.0
    - markupsafe==2.1.1
    - mccabe==0.7.0
    - msgpack==1.0.4
    - mypy-extensions==0.4.3
    - nodeenv==1.7.0
    - packaging==21.3
    - pathspec==0.10.1
    - platformdirs==2.5.2
    - pre-commit==2.20.0
    - pycparser==2.21
    - pydantic==1.10.2
    - pylint==2.15.2
    - pyparsing==3.0.9
    - pytest==7.1.3
    - pytest-cov==3.0.0
    - pyyaml==6.0
    - pyzmq==24.0.0
    - requests==2.28.1
    - roundrobin==0.0.4
    - six==1.16.0
    - sniffio==1.3.0
    - starlette==0.19.1
    - toml==0.10.2
    - tomli==2.0.1
    - tomlkit==0.11.4
    - typing-extensions==4.3.0
    - urllib3==1.26.12
    - uvicorn==0.18.3
    - virtualenv==20.16.5
    - werkzeug==2.2.2
    - wrapt==1.14.1
    - zipp==3.8.1
    - zope-event==4.5.0
    - zope-interface==5.4.0
